# Generated by Django 5.2.6 on 2025-10-13 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_studentprofile_is_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Semester 1', 'Year 2 Semester 1'",
                        max_length=50,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=100)),
                ("credits", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A (4.0)"),
                            ("A-", "A- (3.7)"),
                            ("B+", "B+ (3.3)"),
                            ("B", "B (3.0)"),
                            ("B-", "B- (2.7)"),
                            ("C+", "C+ (2.3)"),
                            ("C", "C (2.0)"),
                            ("C-", "C- (1.7)"),
                            ("D+", "D+ (1.3)"),
                            ("D", "D (1.0)"),
                            ("D-", "D- (0.7)"),
                            ("F", "F (0.0)"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_units",
                        to="achievements.semester",
                    ),
                ),
            ],
        ),
    ]
