# Generated by Django 5.2.6 on 2025-10-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0005_semester_courseunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseunit",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+ (5.0)"),
                    ("A", "A (5.0)"),
                    ("B+", "B+ (4.5)"),
                    ("B", "B (4.0)"),
                    ("C+", "C+ (3.5)"),
                    ("C", "C (3.0)"),
                    ("D+", "D+ (2.5)"),
                    ("D", "D (2.0)"),
                    ("E+", "E+ (1.5)"),
                    ("E-", "E- (1.0)"),
                    ("F", "F (0.0)"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
