# Generated by Django 5.2.6 on 2025-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0006_alter_courseunit_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="cgpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Saved overall CGPA for the student",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_credits",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total recorded credits used in CGPA calculation",
                max_digits=6,
                null=True,
            ),
        ),
    ]
